print-status: False
api:
    name: Wordle
    extension: yml
    dependency:
        update: False
        list:
            web: [Popen,Path]
            local: []
    list: [globals]
    language: EN-US
    git:
        url: https://github.com/SamuelJansen/
        extension: git

    session:
        secret: ${SESSION_SECRET:default}
    api-key:
        secret: ${API_KEY_SECRET:default}
    security:
        secret: ${SECURITY_SECRET:default}
    server:
        scheme: http
        host: 0.0.0.0
        port: 6557
        base-url: /wordle
    scheduler:
        time-zone: ${SCHEDULER_TIMEZONE:Brazil/East}
        enable: ${ENABLE_SCHEDULER_API:True}
        mute-logs: False

word:
    random:
        api-key: ${RANDOM_WORD_API_KEY:default}
        rapid-host: ${RANDOM_WORD_RAPID_HOST:default}
        base-url: ${RANDOM_WORD_BASE_URL:defautl}
        default-timeout-in-seconds: 2
        words-per-request: 2
    data:
        api-key: ${WORD_DATA_API_KEY:default}
        rapid-host: ${WORD_DATA_RAPID_HOST:default}
        base-url: ${WORD_DATA_BASE_URL:defautl}
        default-timeout-in-seconds: 2

match:
    word-lenght: 5
    duration-in-minutes: 4
    total-guesses: 5

swagger:
    # schemes: [${api.server.scheme}] ###- bug
    # host: ${SWAGGER_HOST:${api.server.host}}:${api.server.port} ###- bug
    info:
        title: ${api.name}
        description: A Wordle like game
        version: 0.0.1
        terms-of-service: http://swagger.io/terms/
        contact:
            name: Samuel Jansen
            email: samuel.jansenn@gmail.com
        license:
            name: Apache 2.0 / MIT License
            url: http://www.apache.org/licenses/LICENSE-2.0.html

python:
    version: 3.9
